---
instances:
- https://rss.shab.fun/
- https://vercel.getrss2021.xyz/
- https://rsshub.rssforever.com/
- http://getrss2021.xyz:1200/
- https://rsshub.app/
routes:
- title: JitHub
  path: jike/topic/55e02198dcef9f0e00d7b3c3
# baseUrl: https://raw.githubusercontent.com/wdssmq/proxy_rsshub/main # The Base Url Of xml folder
